<script setup lang="ts">
import { nextTick, ref, watch } from 'vue'
import { Edit3, ExternalLink, Play, Send, Square, Trash2, X } from 'lucide-vue-next'
import type { Auftrag, AuftragStatus, LogZeile } from '../../api/types'
import AuftragFormular from './AuftragFormular.vue'
import { MODUS_LABELS, PROFIL_LABELS, STATUS_LABELS, ZEIT_LABELS, agentChipLabel, datum, dauer, dauerText, kosten, tokens, zeitAusLog, type AuftragFormModel } from './labels'

const props = defineProps<{ auftrag: Auftrag; bearbeitenAktiv: boolean; editForm: AuftragFormModel; busy: boolean; logs: LogZeile[]; jetzt: number; branchLoeschenBestaetigen: boolean }>()
const emit = defineEmits<{ speichern: []; bearbeitenAbbrechen: []; umsetzen: []; statusSetzen: [status: AuftragStatus, meldung: string]; fortsetzen: []; pruefen: []; prErstellen: []; nachfrage: []; starten: []; editieren: []; loeschen: []; stoppen: []; aufraeumen: [branchLoeschen: boolean]; schliessen: [] }>()
const nachfrageText = defineModel<string>('nachfrageText', { required: true })
const umsetzungHinweis = defineModel<string>('umsetzungHinweis', { required: true })
const protokoll = ref<HTMLElement | null>(null)

watch(() => props.logs, async () => { await nextTick(); if (protokoll.value) protokoll.value.scrollTop = protokoll.value.scrollHeight }, { deep: true })
</script>

<template>
  <header class="panel-kopf"><div><span class="mono dim">{{ STATUS_LABELS[auftrag.status].toUpperCase() }}</span><h2>{{ auftrag.titel }}</h2></div><button class="icon-knopf" type="button" aria-label="Schließen" @click="$emit('schliessen')"><X :size="21" /></button></header>
  <div class="detail">
    <AuftragFormular v-if="bearbeitenAktiv" variante="bearbeiten" :form="editForm" :busy="busy" @submit="$emit('speichern')" @abbrechen="$emit('bearbeitenAbbrechen')" />
    <template v-else>
      <div class="detail-chips chips"><span :class="['agent-chip', `agent-${auftrag.agent}`]" :title="auftrag.agent_auto && auftrag.agent_grund ? auftrag.agent_grund : undefined">{{ agentChipLabel(auftrag) }}</span><span class="modus-chip">{{ MODUS_LABELS[auftrag.modus] }}</span><span>{{ PROFIL_LABELS[auftrag.profil] }}</span><span>P{{ auftrag.prioritaet }}</span><span>{{ ZEIT_LABELS[auftrag.zeitfenster] }}</span></div>
      <p v-if="auftrag.agent_auto && auftrag.agent_grund" class="agent-grund mono">{{ auftrag.agent_grund }}</p>
      <section class="detail-block"><h3>Auftrag</h3><p class="prosa">{{ auftrag.text }}</p></section>
      <section v-if="auftrag.status === 'freigabe'" class="detail-block freigabe-block"><h3>Plan zur Freigabe</h3><pre class="plan mono">{{ auftrag.ergebnis || 'Der Plan wurde noch nicht übermittelt.' }}</pre><label>Hinweis zur Umsetzung (optional)<textarea v-model="umsetzungHinweis" rows="3" placeholder="Ergänzung oder Einschränkung für die Umsetzung …" /></label><div class="aktionen"><button class="knopf" type="button" :disabled="busy" @click="$emit('umsetzen')">Umsetzen</button><button class="knopf ghost" type="button" :disabled="busy" @click="$emit('statusSetzen', 'fertig', 'Plan als Bericht behalten')">Nur Bericht behalten</button></div></section>
      <section v-if="auftrag.status === 'unterbrochen'" class="detail-block unterbrochen-block"><h3>Lauf unterbrochen</h3><p class="prosa">{{ auftrag.fehler || 'Der laufende Prozess ist nicht mehr erreichbar.' }}</p><div class="aktionen"><button class="knopf" type="button" :disabled="busy" @click="$emit('fortsetzen')">Fortsetzen</button><button class="knopf ghost" type="button" :disabled="busy" @click="$emit('statusSetzen', 'eingang', 'Auftrag liegt wieder im Eingang')">Erneut in Eingang</button></div></section>
      <dl class="metadaten"><div><dt>ID</dt><dd class="mono">{{ auftrag.id }}</dd></div><div><dt>Status · Reihenfolge</dt><dd>{{ STATUS_LABELS[auftrag.status] }} · {{ auftrag.reihenfolge }}</dd></div><div><dt>Projekt</dt><dd>{{ auftrag.projekt_name }} · {{ auftrag.host }}</dd></div><div><dt>Pfad</dt><dd class="mono">{{ auftrag.projekt }}</dd></div><div><dt>Branch</dt><dd class="mono">{{ auftrag.branch ?? '–' }}</dd></div><div><dt>Worktree</dt><dd class="mono">{{ auftrag.worktree ?? '–' }}</dd></div><div><dt>Sitzung</dt><dd class="mono">{{ auftrag.session_id ?? '–' }}</dd></div><div><dt>Freigegeben</dt><dd>{{ datum(auftrag.freigegeben) }}</dd></div><div><dt>Erstellt</dt><dd>{{ datum(auftrag.erstellt) }}</dd></div><div><dt>Aktualisiert</dt><dd>{{ datum(auftrag.aktualisiert) }}</dd></div><div><dt>Gestartet</dt><dd>{{ datum(auftrag.gestartet) }}</dd></div><div><dt>Beendet</dt><dd>{{ datum(auftrag.beendet) }}</dd></div><div><dt>Dauer</dt><dd class="mono">{{ dauerText(dauer(auftrag, jetzt)) }}</dd></div><div><dt>Kosten</dt><dd class="mono">{{ kosten(auftrag.kosten_usd) }}</dd></div><div><dt>Tokens</dt><dd class="mono">{{ tokens(auftrag.tokens_in) }} ein · {{ tokens(auftrag.tokens_out) }} aus</dd></div><div><dt>Turns</dt><dd>{{ auftrag.turns ?? '–' }}</dd></div><div><dt>Letzte Zeile</dt><dd class="mono">{{ auftrag.letzte_zeile ?? '–' }}</dd></div></dl>
      <section v-if="auftrag.status !== 'freigabe' && auftrag.status !== 'unterbrochen' && (auftrag.ergebnis || auftrag.fehler)" class="detail-block"><h3>{{ auftrag.fehler ? 'Fehler' : 'Ergebnis' }}</h3><p class="prosa" :class="{ 'fehler-text': auftrag.fehler }">{{ auftrag.fehler ?? auftrag.ergebnis }}</p><a v-if="auftrag.diff_url" class="diff-link" :href="auftrag.diff_url" target="_blank" rel="noopener"><ExternalLink :size="14" /> Diff öffnen</a></section>
      <section v-if="auftrag.status === 'fertig' || auftrag.pruefung" class="detail-block pruefung-block"><div class="block-kopf"><h3>Prüfung im Worktree</h3><span class="pruefung-badge" :class="auftrag.pruefung_ok === true ? 'ok' : auftrag.pruefung_ok === false ? 'krit' : 'ohne'">{{ auftrag.pruefung_ok === true ? 'Prüfung ✓' : auftrag.pruefung_ok === false ? 'Prüfung ✗' : 'ohne Prüfung' }}</span></div><div v-if="auftrag.pruefung?.length" class="pruefung-liste"><details v-for="(test, index) in auftrag.pruefung" :key="`${test.befehl}-${index}`" class="pruefung-zeile"><summary><span :class="test.ok ? 'test-ok' : 'test-fehler'">{{ test.ok ? '✓' : '✗' }}</span><code>{{ test.befehl }}</code><span class="mono dim">{{ dauerText(test.dauer_s) }}</span></summary><pre>{{ test.auszug || 'Kein Auszug vorhanden.' }}</pre></details></div><p v-else class="dim ohne-pruefung">Keine Prüfbefehle gefunden.</p><button class="knopf klein ghost" type="button" :disabled="busy" @click="$emit('pruefen')">Erneut prüfen</button></section>
      <section v-if="auftrag.pr_url || (auftrag.status === 'fertig' && auftrag.branch)" class="detail-block pr-block"><h3>Pull Request</h3><template v-if="auftrag.pr_url"><a class="pr-link" :href="auftrag.pr_url" target="_blank" rel="noopener"><ExternalLink :size="14" /> Pull Request auf GitHub öffnen</a><span v-if="auftrag.pr_checks" class="mono pr-checks">{{ auftrag.pr_checks }}</span></template><template v-else><p class="prosa">Pusht den Branch und legt den PR an – gemergt wird nur von dir auf GitHub.</p><p v-if="auftrag.pruefung_ok === false" class="pr-warnung">Prüfung ist rot</p><button class="knopf" type="button" :disabled="busy" @click="$emit('prErstellen')">PR erstellen</button></template></section>
      <section class="detail-block protokoll-block"><div class="block-kopf"><h3>Protokoll</h3><span v-if="auftrag.status === 'laeuft'" class="live-klein"><i /> LIVE</span></div><div ref="protokoll" class="protokoll mono"><p v-for="(zeile, index) in logs" :key="`${zeile.ts}-${index}`" :class="`log-${zeile.art}`"><time>{{ zeitAusLog(zeile.ts) }}</time><span>{{ zeile.text }}</span></p><p v-if="!logs.length" class="dim">Noch keine Protokollzeilen.</p></div></section>
      <div v-if="auftrag.status === 'rueckfrage' || ['fertig', 'fehler', 'abgebrochen'].includes(auftrag.status)" class="nachfrage"><label>{{ auftrag.status === 'rueckfrage' ? 'Antwort / Nachfrage' : 'Nachfrage an dieselbe Sitzung' }}<textarea v-model="nachfrageText" rows="3" placeholder="Nachricht eingeben …" /></label><button class="knopf" type="button" :disabled="busy" @click="$emit('nachfrage')"><Send :size="14" /> Senden</button></div>
      <div class="aktionen detail-aktionen"><template v-if="auftrag.status === 'eingang' || auftrag.status === 'geplant'"><button class="knopf" type="button" :disabled="busy" @click="$emit('starten')"><Play :size="14" /> Starten</button><button class="knopf ghost" type="button" @click="$emit('editieren')"><Edit3 :size="14" /> Bearbeiten</button><button class="knopf gefahr ghost" type="button" :disabled="busy" @click="$emit('loeschen')"><Trash2 :size="14" /> Löschen</button></template><button v-else-if="auftrag.status === 'laeuft'" class="knopf gefahr" type="button" :disabled="busy" @click="$emit('stoppen')"><Square :size="13" /> Stoppen</button><template v-else-if="auftrag.status === 'rueckfrage'"><button class="knopf" type="button" :disabled="busy" @click="$emit('statusSetzen', 'fertig', 'Auftrag als fertig markiert')">Als fertig markieren</button></template><template v-else-if="auftrag.status === 'freigabe' || auftrag.status === 'unterbrochen'" /><template v-else><button class="knopf ghost" type="button" :disabled="busy" @click="$emit('statusSetzen', 'eingang', 'Auftrag liegt wieder im Eingang')">Erneut in Eingang</button><button class="knopf gefahr ghost" type="button" :disabled="busy" @click="$emit('loeschen')"><Trash2 :size="14" /> Löschen</button></template></div>
      <div v-if="['fertig', 'fehler', 'abgebrochen'].includes(auftrag.status) && auftrag.worktree" class="aufraeumen"><button class="knopf ghost" type="button" :disabled="busy" @click="$emit('aufraeumen', false)">Worktree aufräumen</button><button class="branch-loeschen" type="button" :disabled="busy" @click="$emit('aufraeumen', true)">{{ branchLoeschenBestaetigen ? 'Wirklich löschen?' : '… und Branch löschen' }}</button></div>
    </template>
  </div>
</template>

<style scoped src="./auftragDetail.css"></style>
